### PR TITLE
Adapt to curl 7.85.0

### PR DESCRIPTION
**Pull request by 0-wiz-0**
Breaks build in 7.87.0 because of -Werror.

### CODE REVIEW

**Comment by 0-wiz-0** [comment]
This is incomplete.

**Comment by rmind** [comment]
@0-wiz-0: What's wrong with it?

**Comment by 0-wiz-0** [comment]
I couldn't test on my machine, just followed the instructions by curl's deprecation macro. It lead to a different error, see
http://www.ki.nu/pkgsrc/reports/current/NetBSD-9.0/20221223.2326/rvault-0.3nb7/build.log :
```
In function 'http_request',
    inlined from 'http_api_request' at core/keyauth.c:76:6:
core/http_req.c:55:2: error: call to '_curl_easy_setopt_err_string' declared with attribute warning: curl_easy_setopt expects a string ('char *' or char[]) argument for this option [-Werror]
  curl_easy_setopt(curl, CURLOPT_PROTOCOLS_STR, CURLPROTO_HTTPS);
  ^
```

In pkgsrc, I just turned off `-Werror` for rvault for now.
